### ISSUE TITLE
github登录怎么跟本地登录结合起来？

### ISSUE THREAD

**Issue by tomoya92** [kaenry/spring-boot-magneto#1]
你好，谷歌搜到你发到简书上的文章，看了springboot里用springsecurity oauth2的例子，但不是太明白github登录成功了怎么匹配到本地帐户

我写的网站用的是springboot，权限用的是spring-security，现在想把github登录集成进来，但不知道怎么跟自己的用户系统结合，还望指教

**Comment by xmt1139057136** [comment]
[www.xttblog.com](www.xttblog.com)

**Comment by tomoya92** [comment]
@xmt1139057136 你发的网站里没有我问的问题相关的博客

**Comment by xmt1139057136** [comment]
[www.codedq.net](www.codedq.net)
我整理后，把地址发给你，我这里上网不方便，只能访问csdn，github

**Comment by tomoya92** [comment]
@xmt1139057136 好的，感谢

**Comment by tomoya92** [comment]
@kaenry 还没有

**Comment by kaenry** [comment]
@tomoya92 我说一下我的经验，我开发过比如一开始注册帐号，之后要加入微信登录，绑定到已有的帐号，所以我觉得你的需求可能是要做一个类似的功能，绑定github

**Comment by tomoya92** [comment]
@kaenry 对，我之前也做过这样的功能，但现在我用了springsecurity，然后就不知道怎么弄了，而且我还想用springcloud里集成好的oauth2来做，我不知道它们怎么整合的。。

**Comment by kaenry** [comment]
@tomoya92 我做微信的时候是这样做的，绑定微信的链接和微信登录的是一样的，微信登录成功的回调函数里将成功的微信id和已登录的帐号关联，这样就行了，没有现成的模块，需要自己写一些东西，详细的可以进QQ群：112156129。issue我暂时关了
